# Generated by Django 5.0.4 on 2024-05-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_alter_jobpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied',
            name='application',
        ),
        migrations.AddField(
            model_name='applied',
            name='recruiter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='applies_from', to='recruiters.recruiter'),
            preserve_default=False,
        ),
    ]
