# Generated by Django 5.0.4 on 2024-05-05 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_remove_applied_application_applied_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='jobPost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruiters.jobpost'),
            preserve_default=False,
        ),
    ]
