import React from "react";
import game from "/Videos/3d-glassy-abstract-hashtag.webm";
import { BiTestTube } from "react-icons/bi";
import { FiArrowUpRight } from "react-icons/fi";
import { VscGame } from "react-icons/vsc";
import Lottie from 'react-lottie';
import aitest from '../../public/lotties/network robot assistant working on laptop.json';
import cv from '../../public/lotties/beam-levitating-sticker.json';
import work from '/Videos/3d-glassy-abstract-spiral-band-blue.webm';
import { TbFileCv } from "react-icons/tb";
import { RiRobot3Line } from "react-icons/ri";


const Grid: React.FC = () => {

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: aitest, cv,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    }
  };

  const defaultOptions2 = {
    loop: true,
    autoplay: true,
    animationData: cv,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    }
  };

  return (
    <div className="flex flex-col gap-16 md:py-20">
      <h2 className="text-center md:text-3xl lg:text-4xl px-6 max-w-2xl mx-auto font-semibold">Unlock Job Opportunities and Gamify Your Growth with AI</h2>
      <div className="md:px-20 px-6 flex flex-col gap-8">
        <div className="flex flex-col gap-4">
          <div className="bg-[#F6F7FA] flex justify-evenly gap-20 rounded-3xl p-6 w-full">
            <div className="max-md:hidden">
              <Lottie
                options={defaultOptions}
                height={400}
                width={400}
              />
            </div>
            <div className="py-12">
              <div className="bg-[#036BDC] text-white font-semibold text-2xl rounded-xl w-10 h-10 flex items-center justify-center">
                <BiTestTube />
              </div>
              <h3 className="text-3xl font-bold text-gray-800 mt-4">
                Tests generated by AI
              </h3>
              <p className="text-gray-600 mt-2 max-w-80">Figma ipsum component variant main layer. Layer italic group image content shadow frame. Flatten editor vertical image </p>
              <a href="#" className="flex hover:text-[#2b5d93] duration-300 gap-2 items-center text-[#036BDC] mt-4">Learn more <span><FiArrowUpRight /></span></a>
            </div>
          </div>
          <div className="bg-[#F6F7FA] flex gap-20 justify-evenly rounded-3xl p-6 w-full">
            <div className="py-12 mx:mx-20">
              <div className="bg-[#036BDC] text-white font-semibold text-2xl rounded-xl w-10 h-10 flex items-center justify-center">
                <VscGame />
              </div>
              <h3 className="text-2xl font-semibold text-gray-800 mt-4">
                Gamification Points
              </h3>
              <p className="text-gray-600 mt-2 max-w-80">Figma ipsum component variant main layer. Layer italic group image content shadow frame. Flatten editor vertical image </p>
              <a href="#" className="flex hover:text-[#2b5d93] duration-300 gap-2 items-center text-[#036BDC] mt-4">Learn more <span><FiArrowUpRight /></span></a>
            </div>
            <video
              src={game}
              width={400}
              height={400}
              autoPlay
              loop
              muted
              className="max-md:hidden"
            />
          </div>
        </div>
        <div className="flex max-md:flex-col gap-4 justify-evenly w-full">
          <div className="bg-[#F6F7FA] md:w-[48%] gap-6 rounded-3xl p-6">
            <div className="max-md:hidden">
            <Lottie
              options={defaultOptions2}
              height={400}
              width={400}
            />
            </div>
            <div className="py-12">
              <div className="bg-[#036BDC] text-white font-semibold text-2xl rounded-xl w-10 h-10 flex items-center justify-center">
                <TbFileCv />
              </div>
              <h3 className="text-2xl font-semibold text-gray-800 mt-4">
                Create your own CV
              </h3>
              <p className="text-gray-600 mt-2">Figma ipsum component variant mai content </p>
              <a href="#" className="flex hover:text-[#2b5d93] duration-300 gap-2 items-center text-[#036BDC] mt-4">Learn more <span><FiArrowUpRight /></span></a>
            </div>
          </div>
          <div className="bg-[#F6F7FA] md:w-[48%] rounded-3xl p-6">
            <video
              src={work}
              autoPlay
              loop
              muted
              width={400}
              height={400}
              className="max-md:hidden"
            />
            <div className="py-12">
              <div className="bg-[#036BDC] text-white font-semibold text-2xl rounded-xl w-10 h-10 flex items-center justify-center">
                <RiRobot3Line />
              </div>
              <h3 className="text-2xl font-semibold text-gray-800 mt-4">
                Suggest jobs for you
              </h3>
              <p className="text-gray-600 mt-2">Figma ipsum component variant mai content </p>
              <a href="#" className="flex hover:text-[#2b5d93] duration-300 gap-2 items-center text-[#036BDC] mt-4">Learn more <span><FiArrowUpRight /></span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Grid;